### ISSUE TITLE
Not failing gracefully when API user has insufficient permissions

### ISSUE THREAD

**Issue by Mathematicaster** [fortinetdev/terraform-provider-fortios#257]
This is more of a nice-to-have than something essential to operation, but since it caused me to spend a few fruitless hours looking for answers I thought I should submit an issue report.

Steps to replicate:

1. Create a REST API Administrator who does _not_ have read privileges to _Network_ > _Configuration_ in their Admin Profile.
2. Use this Terraform file, editing the provider block if necessary:
```terraform
terraform {
  required_version = "~> 1.3"

  required_providers {
    fortios = {
      source  = "fortinetdev/fortios"
      version = "1.16.0"
    }
  }
}

provider "fortios" {
  # Configure this block or set environment variables (FORTIOS_ACCESS_HOSTNAME, FORTIOS_ACCESS_TOKEN, etc.)
}

data "fortios_system_interface" "port1" {
  name = "port1"
}
```

3. Run `terraform init`.
4. Run `terraform plan`. You should get output similar to the following:
```text
data.fortios_system_interface.port1: Reading...
╷
│ Error: Plugin did not respond
│ 
│   with data.fortios_system_interface.port1,
│   on error.tf line 16, in data "fortios_system_interface" "port1":
│   16: data "fortios_system_interface" "port1" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more
│ details.
╵

Stack trace from the terraform-provider-fortios_v1.16.0 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 20 [running]:
github.com/terraform-providers/terraform-provider-fortios/fortios.dataSourceFlattenSystemInterfaceDhcpRelayIp({0x0?, 0x0?}, 0x272a85b?, {0xd?, 0x0?})
        github.com/terraform-providers/terraform-provider-fortios/fortios/data_source_system_interface.go:1618 +0x8d
github.com/terraform-providers/terraform-provider-fortios/fortios.dataSourceRefreshObjectSystemInterface(0xc0002081f8?, 0xc0013a64e4?)
        github.com/terraform-providers/terraform-provider-fortios/fortios/data_source_system_interface.go:3934 +0x70a
github.com/terraform-providers/terraform-provider-fortios/fortios.dataSourceSystemInterfaceRead(0x0?, {0x25e7220?, 0xc001417b20?})
        github.com/terraform-providers/terraform-provider-fortios/fortios/data_source_system_interface.go:1487 +0x166
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x298a1c0?, {0x298a1c0?, 0xc0013b2b10?}, 0xd?, {0x25e7220?, 0xc001417b20?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource.go:712 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc0001d7960, {0x298a1c0, 0xc0013b2b10}, 0xc000522580, {0x25e7220, 0xc001417b20})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource.go:943 +0x145
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc0000ac660, {0x298a1c0?, 0xc0013b29f0?}, 0xc00139a120)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/grpc_provider.go:1179 +0x38f
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc0000b0280, {0x298a1c0?, 0xc0013b2210?}, 0xc0013b80a0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:658 +0x3ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x26e6a40?, 0xc0000b0280}, {0x298a1c0, 0xc0013b2210}, 0xc0013c4000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:421 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003da000, {0x298cda0, 0xc000610680}, 0xc00139e000, 0xc000c492c0, 0x31cedd0, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc0003da000, {0x298cda0, 0xc000610680}, 0xc00139e000, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-fortios_v1.16.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

You could argue that this is not a bug, but at the very least the `fortinetdev/fortios` plugin shouldn't cause Terraform to spit out invective about your otherwise good plugin.

**Comment by lix-fortinet** [comment]
Hi @Mathematicaster,

Thank you for raising this issue. We will investigate it and improve it in the next release.

Thanks,
Xing

**Comment by MaxxLiu22** [comment]
Hi @Mathematicaster ， Terraform FOS provider version 1.17.0 has released, please check it out. If the issue still occurs, please let me know.
