### ISSUE TITLE
Crash when creating a ressource fortios_routerbgp_neighbor 

### ISSUE THREAD

**Issue by pacrutchet** [fortinetdev/terraform-provider-fortios#304]
Hello,

I'm using the provider 1.18.1 and a Fortigate 6.4.14.

Resource:
```
 # fortios_routerbgp_neighbor.bgp_neighbor["10.37.254.72"] will be created
  + resource "fortios_routerbgp_neighbor" "bgp_neighbor" {
      + activate                          = (known after apply)
      + activate6                         = (known after apply)
      + activate_evpn                     = (known after apply)
      + activate_vpnv4                    = (known after apply)
      + additional_path                   = (known after apply)
      + additional_path6                  = (known after apply)
      + additional_path_vpnv4             = (known after apply)
      + adv_additional_path               = (known after apply)
      + adv_additional_path6              = (known after apply)
      + adv_additional_path_vpnv4         = (known after apply)
      + advertisement_interval            = (known after apply)
      + allowas_in                        = (known after apply)
      + allowas_in6                       = (known after apply)
      + allowas_in_enable                 = (known after apply)
      + allowas_in_enable6                = (known after apply)
      + allowas_in_enable_evpn            = (known after apply)
      + allowas_in_enable_vpnv4           = (known after apply)
      + allowas_in_evpn                   = (known after apply)
      + allowas_in_vpnv4                  = (known after apply)
      + as_override                       = (known after apply)
      + as_override6                      = (known after apply)
      + attribute_unchanged               = (known after apply)
      + attribute_unchanged6              = (known after apply)
      + attribute_unchanged_vpnv4         = (known after apply)
      + bfd                               = (known after apply)
      + capability_default_originate      = (known after apply)
      + capability_default_originate6     = (known after apply)
      + capability_dynamic                = (known after apply)
      + capability_graceful_restart       = (known after apply)
      + capability_graceful_restart6      = (known after apply)
      + capability_graceful_restart_evpn  = (known after apply)
      + capability_graceful_restart_vpnv4 = (known after apply)
      + capability_orf                    = (known after apply)
      + capability_orf6                   = (known after apply)
      + capability_route_refresh          = (known after apply)
      + connect_timer                     = (known after apply)
      + default_originate_routemap        = (known after apply)
      + default_originate_routemap6       = (known after apply)
      + description                       = (known after apply)
      + distribute_list_in                = (known after apply)
      + distribute_list_in6               = (known after apply)
      + distribute_list_in_vpnv4          = (known after apply)
      + distribute_list_out               = (known after apply)
      + distribute_list_out6              = (known after apply)
      + distribute_list_out_vpnv4         = (known after apply)
      + dont_capability_negotiate         = (known after apply)
      + dynamic_sort_subtable             = "false"
      + ebgp_enforce_multihop             = "enable"
      + ebgp_multihop_ttl                 = (known after apply)
      + filter_list_in                    = (known after apply)
      + filter_list_in6                   = (known after apply)
      + filter_list_in_vpnv4              = (known after apply)
      + filter_list_out                   = (known after apply)
      + filter_list_out6                  = (known after apply)
      + filter_list_out_vpnv4             = (known after apply)
      + get_all_tables                    = "false"
      + holdtime_timer                    = (known after apply)
      + id                                = (known after apply)
      + interface                         = (known after apply)
      + ip                                = "10.37.254.72"
      + keep_alive_timer                  = (known after apply)
      + link_down_failover                = (known after apply)
      + local_as                          = (known after apply)
      + local_as_no_prepend               = (known after apply)
      + local_as_replace_as               = (known after apply)
      + maximum_prefix                    = (known after apply)
      + maximum_prefix6                   = (known after apply)
      + maximum_prefix_evpn               = (known after apply)
      + maximum_prefix_threshold          = (known after apply)
      + maximum_prefix_threshold6         = (known after apply)
      + maximum_prefix_threshold_evpn     = (known after apply)
      + maximum_prefix_threshold_vpnv4    = (known after apply)
      + maximum_prefix_vpnv4              = (known after apply)
      + maximum_prefix_warning_only       = (known after apply)
      + maximum_prefix_warning_only6      = (known after apply)
      + maximum_prefix_warning_only_evpn  = (known after apply)
      + maximum_prefix_warning_only_vpnv4 = (known after apply)
      + next_hop_self                     = (known after apply)
      + next_hop_self6                    = (known after apply)
      + next_hop_self_rr                  = (known after apply)
      + next_hop_self_rr6                 = (known after apply)
      + next_hop_self_vpnv4               = (known after apply)
      + override_capability               = (known after apply)
      + passive                           = (known after apply)
      + prefix_list_in                    = (known after apply)
      + prefix_list_in6                   = (known after apply)
      + prefix_list_in_vpnv4              = (known after apply)
      + prefix_list_out                   = (known after apply)
      + prefix_list_out6                  = (known after apply)
      + prefix_list_out_vpnv4             = (known after apply)
      + remote_as                         = 65515
      + remove_private_as                 = (known after apply)
      + remove_private_as6                = (known after apply)
      + remove_private_as_evpn            = (known after apply)
      + remove_private_as_vpnv4           = (known after apply)
      + restart_time                      = (known after apply)
      + retain_stale_time                 = (known after apply)
      + route_map_in                      = "AZU-CH-HUB-1-IN"
      + route_map_in6                     = (known after apply)
      + route_map_in_evpn                 = (known after apply)
      + route_map_in_vpnv4                = (known after apply)
      + route_map_out                     = "AZU-CH-HUB-1-OUT"
      + route_map_out6                    = (known after apply)
      + route_map_out6_preferable         = (known after apply)
      + route_map_out_evpn                = (known after apply)
      + route_map_out_preferable          = (known after apply)
      + route_map_out_vpnv4               = (known after apply)
      + route_map_out_vpnv4_preferable    = (known after apply)
      + route_reflector_client            = (known after apply)
      + route_reflector_client6           = (known after apply)
      + route_reflector_client_evpn       = (known after apply)
      + route_reflector_client_vpnv4      = (known after apply)
      + route_server_client               = (known after apply)
      + route_server_client6              = (known after apply)
      + route_server_client_evpn          = (known after apply)
      + route_server_client_vpnv4         = (known after apply)
      + send_community                    = (known after apply)
      + send_community6                   = (known after apply)
      + send_community_evpn               = (known after apply)
      + send_community_vpnv4              = (known after apply)
      + shutdown                          = (known after apply)
      + soft_reconfiguration              = "enable"
      + soft_reconfiguration6             = (known after apply)
      + soft_reconfiguration_evpn         = (known after apply)
      + soft_reconfiguration_vpnv4        = (known after apply)
      + stale_route                       = (known after apply)
      + strict_capability_match           = (known after apply)
      + unsuppress_map                    = (known after apply)
      + unsuppress_map6                   = (known after apply)
      + update_source                     = "port2"
      + weight                            = (known after apply)
    }

```
Crash log:
Stack trace from the terraform-provider-fortios_v1.18.1 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 91 [running]:
github.com/terraform-providers/terraform-provider-fortios/fortios.expandRouterBgpNeighbor(0x1b5fb80?, {0x1b19240?, 0xc0002f6c18?}, {0x1c47901, 0x8}, {0xc0002f5156, 0x7})
        github.com/terraform-providers/terraform-provider-fortios/fortios/resource_router_bgp.go:7416 +0x8a85
github.com/terraform-providers/terraform-provider-fortios/fortios.getObjectRouterBgp(0x2?, 0x0, {0xc0002f5156, 0x7})
        github.com/terraform-providers/terraform-provider-fortios/fortios/resource_router_bgp.go:11561 +0x3bd9
github.com/terraform-providers/terraform-provider-fortios/fortios.resourceRouterBgpUpdate(0xc0001d6080, {0x1b06ae0?, 0xc00182ce30})
        github.com/terraform-providers/terraform-provider-fortios/fortios/resource_router_bgp.go:2292 +0x165
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x1ed4d60?, {0x1ed4d60?, 0xc001340660?}, 0xd?, {0x1b06ae0?, 0xc00182ce30?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:729 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0008fc0e0, {0x1ed4d60, 0xc001340660}, 0xc0010b0c30, 0xc000134f00, {0x1b06ae0, 0xc00182ce30})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:847 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00046c750, {0x1ed4d60?, 0xc001340540?}, 0xc0012ff590)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00013a0a0, {0x1ed4d60?, 0xc001307d10?}, 0xc0000ec5b0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1c0d560?, 0xc00013a0a0}, {0x1ed4d60, 0xc001307d10}, 0xc0000ec540, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000484000, {0x1ed8880, 0xc00029e680}, 0xc00164a000, 0xc000c57350, 0x2781200, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc000484000, {0x1ed8880, 0xc00029e680}, 0xc00164a000, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-fortios_v1.18.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

Can you help ?

Thanks !

**Comment by lix-fortinet** [comment]
Hi @pacrutchet,

Thank you for raising this issue. Did you configure the resource `resource_router_bgp` with the variable `neighbor`? If so, could I know how you configured this variable? 

Thanks,
Xing

**Comment by pacrutchet** [comment]
Thanks for coming back to me, I did the following resources:
```
resource "fortios_router_bgp" "bgp" {
  as        = local.router.bgp.as
  router_id = local.router.bgp.router_id

  dynamic "network" {
    for_each = local.router.bgp.network
    content {
      id   = network.key
      prefix = network.value.prefix
    }
  }

  dynamic "redistribute" {
    for_each = local.router.bgp.redistribute
    content {
      name   = redistribute.key
      status = redistribute.value.status
    }
  }

  dynamic "redistribute6" {
    for_each = local.router.bgp.redistribute
    content {
      name   = redistribute6.key
      status = "disable"
    }
  }

  neighbor {}

  neighbor {}

  dynamic_sort_subtable = true
  depends_on = [
    fortios_router_accesslist.access_list,
    fortios_router_routemap.route_map
  ]
}
```

In the past I wasn't allowed to not specify a neighbor block. Has this change ?

Regards,
Pierre

**Comment by pacrutchet** [comment]
removing the neighbor block fixed the issue.

Thanks a lot for your help!

**Comment by lix-fortinet** [comment]
Hi @pacrutchet,

Thank you for your quick response. `neighbor` block is optional for a long time, did you get the requirement message on the Terraform plan stage? But, even your configuration should not cause this crash issue. I tested on my side and did not reproduce it. Could I know your Terraform version? So that I can investigate it and check whether it has a potential issue.

Thanks,
Xing
